FROM ad-acados:latest

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive

ENV QT_DEBUG_PLUGINS=1
ENV QT_QPA_PLATFORM=xcb

SHELL ["/bin/bash", "-c"]

################################
# Extra dependencies
################################
RUN apt-get update && apt-get install -y \
    nlohmann-json3-dev \
    libncurses5-dev \
    libncursesw5-dev \
    software-properties-common \
    lua5.1 \
    luarocks

RUN pip uninstall -y PyQt5 && \
    apt-get install -y python3-pyqt5 python3-venv

RUN add-apt-repository ppa:neovim-ppa/unstable && \
    apt-get update && \
    apt-get install -y neovim

RUN add-apt-repository ppa:ubuntu-toolchain-r/ppa -y && \
    apt-get update && \
    apt-get install -y g++-13 gcc-13

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
