services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-container
    hostname: dev-container
    ports:
      - 11313:11313
    runtime: nvidia
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_HOSTNAME=ros-simulator
      - ROS_MASTER_URI=http://ros-simulator:11313
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - mynetwork
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          cpus: 16
          memory: 8G

networks:
  mynetwork:
    driver: bridge
